import dayjs from "dayjs";

export const QuizData = [
  {
    campaignType: "quiz",
    submissions: [
      {
        id: 1,
        userName: "Ali Khan",
        userEmail: "ali@gmail.com",
        phoneNumber: "03111223344",
        submittedDate: dayjs().subtract(2, "days").format("YYYY/MM/DD"),
      },
      {
        id: 2,
        userName: "Sara Ali",
        userEmail: "sara@gmail.com",
        phoneNumber: "03211223344",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
      {
        id: 3,
        userName: "John Doe",
        userEmail: "john@gmail.com",
        phoneNumber: "03031234567",
        submittedDate: dayjs().subtract(3, "days").format("YYYY/MM/DD"),
      },
      {
        id: 4,
        userName: "Jane Doe",
        userEmail: "jane@gmail.com",
        phoneNumber: "03231234567",
        submittedDate: dayjs().subtract(2, "days").format("YYYY/MM/DD"),
      },
      {
        id: 5,
        userName: "Mike Ross",
        userEmail: "mike@gmail.com",
        phoneNumber: "03012345678",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
      {
        id: 6,
        userName: "Rachel Zane",
        userEmail: "rachel@gmail.com",
        phoneNumber: "03023456789",
        submittedDate: dayjs().subtract(4, "days").format("YYYY/MM/DD"),
      },
      {
        id: 7,
        userName: "Harvey Specter",
        userEmail: "harvey@gmail.com",
        phoneNumber: "03234567890",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
      {
        id: 8,
        userName: "Donna Paulsen",
        userEmail: "donna@gmail.com",
        phoneNumber: "03345678901",
        submittedDate: dayjs().subtract(5, "days").format("YYYY/MM/DD"),
      },
      {
        id: 9,
        userName: "Louis Litt",
        userEmail: "louis@gmail.com",
        phoneNumber: "03456789012",
        submittedDate: dayjs().subtract(2, "days").format("YYYY/MM/DD"),
      },
      {
        id: 10,
        userName: "Jessica Pearson",
        userEmail: "jessica@gmail.com",
        phoneNumber: "03567890123",
        submittedDate: dayjs().subtract(3, "days").format("YYYY/MM/DD"),
      },
      {
        id: 11,
        userName: "Katrina Bennett",
        userEmail: "katrina@gmail.com",
        phoneNumber: "03678901234",
        submittedDate: dayjs().subtract(6, "days").format("YYYY/MM/DD"),
      },
      {
        id: 12,
        userName: "Benjamin Wheeler",
        userEmail: "benjamin@gmail.com",
        phoneNumber: "03789012345",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
    ],
  },
];

export const WebScanData = [
  {
    campaignType: "webScan",
    submissions: [
      {
        id: 1,
        userName: "Ali Khan",
        userEmail: "ali@gmail.com",
        phoneNumber: "03111223344",
        channel: "Google",
        submittedDate: dayjs().subtract(2, "days").format("YYYY/MM/DD"),
      },
      {
        id: 2,
        userName: "Sara Ali",
        userEmail: "sara@gmail.com",
        phoneNumber: "03211223344",
        channel: "Facebook",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
      {
        id: 3,
        userName: "John Doe",
        userEmail: "john@gmail.com",
        phoneNumber: "03031234567",
        channel: "Google",
        submittedDate: dayjs().subtract(3, "days").format("YYYY/MM/DD"),
      },
      {
        id: 4,
        userName: "Jane Doe",
        userEmail: "jane@gmail.com",
        phoneNumber: "03231234567",
        channel: "Facebook",
        submittedDate: dayjs().subtract(2, "days").format("YYYY/MM/DD"),
      },
      {
        id: 5,
        userName: "Mike Ross",
        userEmail: "mike@gmail.com",
        phoneNumber: "03012345678",
        channel: "Youtube",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
      {
        id: 6,
        userName: "Rachel Zane",
        userEmail: "rachel@gmail.com",
        phoneNumber: "03023456789",
        channel: "Google",
        submittedDate: dayjs().subtract(4, "days").format("YYYY/MM/DD"),
      },
      {
        id: 7,
        userName: "Harvey Specter",
        userEmail: "harvey@gmail.com",
        phoneNumber: "03234567890",
        channel: "Facebook",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
      {
        id: 8,
        userName: "Donna Paulsen",
        userEmail: "donna@gmail.com",
        phoneNumber: "03345678901",
        channel: "Google",
        submittedDate: dayjs().subtract(5, "days").format("YYYY/MM/DD"),
      },
      {
        id: 9,
        userName: "Louis Litt",
        userEmail: "louis@gmail.com",
        phoneNumber: "03456789012",
        channel: "Facebook",
        submittedDate: dayjs().subtract(2, "days").format("YYYY/MM/DD"),
      },
      {
        id: 10,
        userName: "Jessica Pearson",
        userEmail: "jessica@gmail.com",
        phoneNumber: "03567890123",
        channel: "Youtube",
        submittedDate: dayjs().subtract(3, "days").format("YYYY/MM/DD"),
      },
      {
        id: 11,
        userName: "Katrina Bennett",
        userEmail: "katrina@gmail.com",
        phoneNumber: "03678901234",
        channel: "Google",
        submittedDate: dayjs().subtract(6, "days").format("YYYY/MM/DD"),
      },
      {
        id: 12,
        userName: "Benjamin Wheeler",
        userEmail: "benjamin@gmail.com",
        phoneNumber: "03789012345",
        channel: "Youtube",
        submittedDate: dayjs().subtract(1, "day").format("YYYY/MM/DD"),
      },
    ],
  },
];
